version: '3.4'

services:
  insightsproxy:
    # run insightsproxy
    # forwarding local:1337 to its 1337
    # insights proxy needs access tp automationhubui:8002 (and/or localhost:8002)
    # image: docker.io/redhatinsights/insights-proxy
    image: galaxy-dev/insights-proxy
    #    build:
    #      context: '.'
    #      dockerfile: docker/insights-proxy/Dockerfile
    ports:
      - '1337:1337'
    depends_on:
      - galaxy-api

  ansiblehubui:
    # build/run an image with npm (reused insightsproxy image?)
    # forward localhost:8002 to container:8002
    #
    image: galaxy-dev/ansiblehubui
    build:
      context: '.'
      dockerfile: docker/ansiblehubui/Dockerfile
    env_file:
      - ./docker/ansiblehubui/env
    ports:
      - '8002:8002'
    volumes:
      - ./ansible-hub-ui:/code/ansible-hub-ui
    depends_on:
      - insightsproxy
