version: '3.4'

volumes:
  postgres_data: {}
  redis_data: {}
  pulp_data: {}
  prometheus_data: {}

services:

  galaxy-api:
    image: galaxy-dev/galaxy-api
    build:
      context: .
      dockerfile: docker/galaxy-api/Dockerfile
    env_file:
      - ./docker/galaxy-api/env
    ports:
      - '5001:8000'
    volumes:
      - ./galaxy-api:/code/galaxy-api
    depends_on:
      - postgres
      - pulp-api

  pulp-api:
    image: galaxy-dev/pulp
    build:
      context: .
      dockerfile: docker/pulp/Dockerfile
    env_file:
      - ./docker/pulp/env
    command: ['run', 'api']
    ports:
      - '5002:8000'
    volumes:
      - pulp_data:/data
    depends_on:
      - postgres
      - redis

  pulp-resource-manager:
    image: galaxy-dev/pulp
    env_file:
      - ./docker/pulp/env
    command: ['run', 'resource-manager']
    volumes:
      - pulp_data:/data
    depends_on:
      - postgres
      - redis

  pulp-worker:
    image: galaxy-dev/pulp
    env_file:
      - ./docker/pulp/env
    command: ['run', 'worker']
    volumes:
      - ./docker/importer-plugins:/code/importer-plugins
      - pulp_data:/data
    depends_on:
      - postgres
      - redis

  pulp-content-app:
    image: galaxy-dev/pulp
    env_file:
      - ./docker/pulp/env
    command: ['run', 'content-app']
    volumes:
      - pulp_data:/data
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:11
    ports:
      - '5432:5432'
    volumes:
      - ./docker/postgres/initdb.d/:/docker-entrypoint-initdb.d:ro
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:5
    volumes:
      - redis_data:/data

  prometheus:
    image: prom/prometheus
    ports:
      - '9090:9090'
    volumes:
      - ./docker/prometheus/:/etc/prometheus
      - prometheus_data:/prometheus
    depends_on:
      - galaxy-api
