version: '3.4'

volumes:
  prometheus_data: {}
  grafana_data: {}

services:
  prometheus:
    image: prom/prometheus
    env_file:
      - ./docker/prometheus/env
    ports:
      - '9090:9090'
    volumes:
      - ./docker/prometheus/:/etc/prometheus
      - prometheus_data:/prometheus
    depends_on:
      - galaxy-api

  grafana:
    image: grafana/grafana
    # env_file:
    #   - ./docker/prometheus/env
    ports:
      - '3000:3000'
    volumes:
      # - ./docker/prometheus/:/etc/prometheus
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
