
FROM docker.io/redhatinsights/insights-proxy

# ENV PATH="/venv/bin:$PATH"
ENV SPANDX_CONFIG="/etc/local-frontend-and-api.js"
# COPY docker/galaxy-api/entrypoint.sh /entrypoint
# ENTRYPOINT [ "/entrypoint" ]
CMD npm run start
